# Samit Bhisikar
## Practical 3
## A-A3-33

In [1]:
import pandas as pd
data = pd.read_csv('enjoy.csv')
display(data.head())

     Sky AirTemp Humidity    Wind Water Forecast EnjoySport
0  Sunny    Warm   Normal  Strong  Warm     Same        Yes
1  Sunny    Warm     High  Strong  Warm     Same        Yes
2  Rainy    Cold     High  Strong  Warm   Change         No
3  Sunny    Warm     High  Strong  Cool   Change        Yes
4  Sunny    Cold   Normal    Weak  Warm     Same         No

In [2]:
data.tail()

      Sky AirTemp Humidity    Wind Water Forecast EnjoySport
5  Cloudy    Warm   Normal    Weak  Warm     Same         No
6   Sunny    Warm   Normal    Weak  Cool     Same        Yes
7   Rainy    Warm     High    Weak  Cool   Change         No
8   Sunny    Warm   Normal  Strong  Cool     Same        Yes
9   Sunny    Warm     High    Weak  Warm     Same        Yes

In [3]:
data.shape

(10, 7)

In [4]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [5]:
import numpy as np

def find_s(X, y):
    hypothesis = None
    print("Initial hypothesis: ", hypothesis)

    for i in range(len(X)):
        if y[i] == 'Yes':
            if hypothesis is None:
                hypothesis = np.copy(X[i])
            else:
                for j in range(len(hypothesis)):
                    if hypothesis[j] != X[i][j]:
                        hypothesis[j] = '?'
        print(f"\nHypothesis after instance {i+1}:")
        print(hypothesis)
    return hypothesis
final_hypothesis = find_s(X, y)
print("\nFinal Specific Hypothesis: ", final_hypothesis)

Initial hypothesis:  None

Hypothesis after instance 1:
['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']

Hypothesis after instance 2:
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

Hypothesis after instance 3:
['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']

Hypothesis after instance 4:
['Sunny' 'Warm' '?' 'Strong' '?' '?']

Hypothesis after instance 5:
['Sunny' 'Warm' '?' 'Strong' '?' '?']

Hypothesis after instance 6:
['Sunny' 'Warm' '?' 'Strong' '?' '?']

Hypothesis after instance 7:
['Sunny' 'Warm' '?' '?' '?' '?']

Hypothesis after instance 8:
['Sunny' 'Warm' '?' '?' '?' '?']

Hypothesis after instance 9:
['Sunny' 'Warm' '?' '?' '?' '?']

Hypothesis after instance 10:
['Sunny' 'Warm' '?' '?' '?' '?']

Final Specific Hypothesis:  ['Sunny' 'Warm' '?' '?' '?' '?']

# Candidate elimination Algorithm

In [6]:
def candidate_elimination(concepts,target):
    specific = concepts[0].copy()
    general=[["?" for i in range(len(specific))]]
    print("Initial Specific Hypothesis: ", specific)
    print("Initial General Hypothesis: ", general)

    for i,h in enumerate(concepts):
        if target[i]=="Yes":
            for x in range(len(specific)):
                if h[x]!=specific[x]:
                    specific[x]='?'
        else:
          for x in range(len(specific)):
            if h[x]!=specific[x]:
              general.append(["?" if j!=x else specific[x] for j in range(len(specific))])

          print("\nExample",i+1)
          print("S=",specific)
          print("G=",general)
    return specific,general
S,G=candidate_elimination(X,y)
print("\nFinal Specific Hypothesis: ", S)
print("Final General Hypothesis: ", G)

for g in G:
  print(g)

Initial Specific Hypothesis:  ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same']
Initial General Hypothesis:  [['?', '?', '?', '?', '?', '?']]

Example 3
S= ['Sunny' 'Warm' '?' 'Strong' 'Warm' 'Same']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same']]

Example 5
S= ['Sunny' 'Warm' '?' 'Strong' '?' '?']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 6
S= ['Sunny' 'Warm' '?' 'Strong' '?' '?']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Example 8
S= ['Sunny' 'Warm' '?' '?' '?' '?']
G= [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]

Final Specific Hypothesis:  ['Sunny' 'Warm' '?' '?' '?' '?']
Final General Hypothesis:  [['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', 'Same'], ['?', 'Warm', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', 'Strong', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['Sunny', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?'], ['?', '?', '?', '?', '?', '?']]
['?', '?', '?', '?', '?', '?']
['Sunny', '?', '?', '?', '?', '?']
['?', 'Warm', '?', '?', '?', '?']
['?', '?', '?', '?', '?', '?']
['?', '?', '?', '?', '?', 'Same']
['?', 'Warm', '?', '?', '?', '?']
['?', '?', '?', '?', '?', '?']
['?', '?', '?', 'Strong', '?', '?']
['?', '?', '?', '?', '?', '?']
['?', '?', '?', '?', '?', '?']
['Sunny', '?', '?', '?', '?', '?']
['?', '?', '?', '?', '?', '?']
['?', '?', '?', 'Strong', '?', '?']
['?', '?', '?', '?', '?', '?']
['?', '?', '?', '?', '?', '?']
['Sunny', '?', '?', '?', '?', '?']
['?', '?', '?', '?', '?', '?']
['?', '?', '?', '?', '?', '?']
['?', '?', '?', '?', '?', '?']
['?', '?', '?', '?', '?', '?']